### ISSUE TITLE
integrate-signup-with-github

### ISSUE THREAD

**Issue by Remi-dee** [annonymousauthority/P2PCoder#114]

**Comment by NAJIB-B** [comment]
@annonymousauthority Can I create another path --> "/app/api/auth/" to implement the github sign in

**Comment by annonymousauthority** [comment]
> @annonymousauthority To integrate the signup with github, since the app is already using firebase I want to implement it with firebase. But I can't access the api keys, since them are in a ".env" file. So how do teams share api keys.

@Remi-dee is on this issue @NAJIB-B. You also don't need access to the api key to write it, if you do, you can create an app on Firebase, utilize your own api keys and test
