### ISSUE TITLE
codes of various files are linked

### ISSUE THREAD

**Issue by 7malikk** [annonymousauthority/P2PCoder#191]
## Expected Behaviour

The user should be able to write tab-specific codes

## Current Behaviour 
When users update the codes in one tab, said update occurs in other tabs

## Demo
![bug](https://github.com/annonymousauthority/P2PCoder/assets/75104021/0aabf63d-942b-4f54-b5d4-5e6d545d7b87)

**Comment by babblebey** [comment]
Hey @7malikk 

I don't think it is necessarily a bug though, the functionality that holds the current state of code per tab is just not in-place yet.

Code Sample
```javascript
// src\app\page.js

{items[0]?.active && items[0].title === 'Welcome' ? (
    //.....
) : items.filter((e) => e.active)[0] ? (
    <CodingEditor language={items.filter((e) => e.active)[0].ext} />
) : (
    //.....
)}
```

Kindly note that `CodingEditor` component only receives `language` as prop, nothing else. 

I believe the code state will be store per tab will be stored in a Firebase firestore (Database) `document` to hold the code state which can in turn be passed into the  `CodingEditor` component to used in the `MonacoEditor` component's `value` prop.

But currently, the state of the code per tab is being managed internally within the `CodingEditor` component.

```javascript
// src\components\codingEditor.js

function CodingEditor({ language }) {
  //....
  const [code, setCode] = useState(
    '// Welcome to P2P Coder, a Community Prepared Platform...'
  );
  //....
  return (
    <div>
      <MonacoEditor
        //....
        language={
          language === '.js'
            ? 'javascript'
            : language === '.css'
            ? 'css'
            : language === '.html'
            ? 'html'
            : 'javascript'
        }
        //....
        value={code}
        //....
      />
    </div>
  );
}
```

It's just a temporary thing I guess!
