### ISSUE TITLE
Session cancellation and local storage update on page refresh

### ISSUE THREAD

**Issue by Ibhassan01** [annonymousauthority/P2PCoder#227]
Session should persist and not automatically cancel upon page refresh

Code should be updated and stored in local storage upon page refresh

**Comment by Oyeins-GUI** [comment]
Please how can I start the development server locally. I'm getting this error when I try to do so.
`
Error: Cannot find module 'metadata.js'
`

**Comment by annonymousauthority** [comment]
@Oyeins-GUI `npm run stage` or `npm run dev` after `npm install`

**Comment by Oyeins-GUI** [comment]
![persist to local storage](https://github.com/annonymousauthority/P2PCoder/assets/104744427/4ebfcbd5-39a0-4ebe-b1ff-ddc591c29d3a)
still getting same error

**Comment by Oyeins-GUI** [comment]
![p2pcoder](https://github.com/annonymousauthority/P2PCoder/assets/104744427/58b71ecd-7a6b-4534-88c0-536ee827769c)
still getting same error
