### ISSUE TITLE
Conflicting Package Managers Warning: Remove package-lock.json

### ISSUE THREAD

**Issue by babblebey** [annonymousauthority/P2PCoder#68]
I encountered a warning message in the console after running `yarn install` in my fork of the project. The warning states that there is a `package-lock.json` file present, which suggests the use of a different package manager alongside Yarn. The warning advises against mixing package managers to prevent resolution inconsistencies caused by unsynchronized lock files.

Steps to Reproduce:
1. Run `yarn install` in the project directory.
2. Observe the warning message in the console.

Expected Behavior:
Running `yarn install` should immediately install all project dependencies and not display any warnings related to conflicting package managers.

Actual Behavior:
After executing the command, the following warning message is displayed in the console:

```
yarn install v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

Additional Information:
1. I have verified that the project's package.json file is correctly set up for Yarn.
2. The `package-lock.json` file was likely generated by another package manager, best guess: npm.

Suggested Solution:
To resolve this warning and avoid potential issues with package resolution, it is recommended to remove the `package-lock.json` file from the project. This can be done by executing the following command:

```
rm package-lock.json
```

Alternatively, considering the project encourages usages of multiple package managers (i.e. npm, pnpm, yarn), we can safely delete the `package-lock.json` file manually.

Once the `package-lock.json` file is removed, running `yarn install` should proceed without displaying the warning.

Please let me know if I can submit a PR which implements this solution!

**Comment by annonymousauthority** [comment]
Hi @babblebey I'm not sure that's a huge consideration currently, as we're currently utilizing npm. While our current objective is to achieve deterministic build on all environment. we could look at this enhancement feature in the future.

**Comment by babblebey** [comment]
Sure thing!
