### ISSUE TITLE
Move /app/font folder to 'src' directory and abstract fonts usage

### ISSUE THREAD

**Issue by babblebey** [annonymousauthority/P2PCoder#69]
In the current setup of the project, there is a font folder located at `/app` that is intended for storing font assets. However, having this folder within the `/app` directory implies that it can potentially be accessed as a route, which is not the intended behavior. Therefore, I would like to suggest moving the `/app/fonts` folder to the `src` directory to prevent it from being thought/exposed as a route and remains as a static asset within the project.

By moving the `/app/fonts` folder to the `src` directory, we maintain a more organized structure and prevent potential route conflicts.

Also, the `/app/fonts` folder should have an `index.js` file inside it to abstract the usage of font. We can configure/export our font(s) using the `localFont` function from `next/font/local` within this file. Like so.. 

```javascript
// src/fonts/index.js

import localFont from "next/font/local";

const nohemi = localFont({
  src: [
    {
      path: "./Nohemi/Nohemi-Black-BF6438cc565e67b.woff",
      weight: "900",
      style: "black",
    },
    ........
  ],
  variable: "--font-nohemi",
});

export { nohemi };
```

This abstraction will help us maintain a cleaner structure, do away with the `app/localFont` folder considering that we can now import the font straight into any file we intend directly from the `/src/fonts` folder like so:

```javascript
// app/layout.js

import { nohemi } from "../fonts";
```

This also allows easy addition of more fonts as required.

**Comment by annonymousauthority** [comment]
Ok, well the fonts folder can be collocated in the app directory in Nextjs13. It wouldn't register it as a page
