### ISSUE TITLE
Adding "Tab Renaming" functionality to the tabs in the Editor Screen

### ISSUE THREAD

**Issue by babblebey** [annonymousauthority/P2PCoder#80]
I would like to add a "Tab Renaming" functionality to the Editor Screen's Tabs. 

The Rename of each tabs will be triggered by a `onDoubleClick` event.

**Implementation Approach:**

1. I will add a new `handleTabRename` handler function similar to the ones for closing and setting tab to active
2. Set up all functionalities within this functions
3. Drill the function down through props to the `tabBarItem` where the functionality can be triggered with a `onDoubleClick` event from the span element that holds the tab title

**Comment by annonymousauthority** [comment]
That'll be perfect! Let's go!

**Comment by babblebey** [comment]
Yes Sir.

PR's submitted!
